## Logging 설정 ###
# Spring Security 디버그 로깅
logging:
  level:
    org:
      springframework:
        security: DEBUG
        # 필터 체인 상세 로그
        web:
          FilterChainProxy: DEBUG
          # 인증/인가 상세 로그
          access:
            interceptor:
              FilterSecurityInterceptor: TRACE

### MySql 설정 ###
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.179.175.228:13306/taskflow?serverTimezone=Asia/Seoul

### MyBatis 설정 ###
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.taskflow.dto
  map-underscore-to-camel-case: true
