### JWT 보안 설정 ###
jwt: 
  secretKey: lw6nVU8mexze+AunmFCBDtT/yK2Lvf07JO79Ze1ctYD5lEoYgvLjGts97BWFiqrFF1qIpeKBZ02P1nwAOEgunA==
  expiration: 
    access: 600000 # 10분
    refresh: 604800000 # 7일

### MySql 보안 설정 ##
spring:
  datasource: 
    username: taskflow_user
    password: abc123123

### Perplexity API 설정 ###
perplexity: 
  api-key: ""